language: python
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy 
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests
script: nosetests -vs tests/ --all-modules --with-coverage --cover-erase --cover-package=.
services: mongodb
before_script:
  - sleep 15

notifications:
  slack: unshredit:2nm3MUsOgq9Bz9bqDPAOPn7S

after_success:
  - coveralls
